
GET http://localhost:8000/

//users
###
GET http://localhost:8000/api/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aWN0b3IiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgxOTY1OTR9.jJ_hArU1Sl_KSna9GVVtcwscUgigPaAUOFJtEPNt3Dw

###
# Get users by id
GET http://localhost:8000/api/users/8

# Create a user
###
POST http://localhost:8000/api/auth/register
Content-Type: application/json

{
    "username": "victor",
    "user_id": 9,
    "password": "1234",
    "role": "admin"

}

###

POST http://localhost:8000/api/auth/login
Content-Type: application/json

{
    "username": "victor",
    "password": "1234"

}

###
PUT http://localhost:8000/api/users/8
Content-Type: application/json

{
    "name": "James kibe",
    "email": "doe@gmail.com",
    "phone_number": "254712345678",
    "password": "password",
    "address_id": 6
}

###
DELETE http://localhost:8000/api/users/7
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aWN0b3IiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgxOTY1OTR9.jJ_hArU1Sl_KSna9GVVtcwscUgigPaAUOFJtEPNt3Dw


// get a single state
###
GET  http://localhost:8000/api/states/2

###
# Get all states
GET http://localhost:8000/api/states
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aWN0b3IiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgxOTExMjh9.pbdiJkgEf8yLdRC32iCmIV2hA8w9Nnm0Sl_SD6XNQHw


###

//create state
POST http://localhost:8000/api/states
Content-Type: application/json

{
    "name": "togo",
    "code": "255"
   
 }

###


PUT http://localhost:8000/api/states/1
Content-Type: application/json

{
    "name": "mwea"
}

###
DELETE  http://localhost:8000/api/states/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aWN0b3IiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgxOTExMjh9.pbdiJkgEf8yLdRC32iCmIV2hA8w9Nnm0Sl_SD6XNQHw


//city
###
GET http://localhost:8000/api/cities
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aWN0b3IiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgxOTY1OTR9.jJ_hArU1Sl_KSna9GVVtcwscUgigPaAUOFJtEPNt3Dw

###
GET  http://localhost:8000/api/cities/4

###
//create city

POST http://localhost:8000/api/cities
Content-Type: application/json

{
    "name": "kampala",
    "state_id": 3
 }

###

PUT http://localhost:8000/api/cities/4
Content-Type: application/json

{
    "name": "lilongwe",
    "code": "255"

}
//delete cities
###
DELETE  http://localhost:8000/api/cities/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aWN0b3IiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgxODM1OTR9.gFFYD_XJ_H8lybnNpI9xTXZp29li7N3XP8pB-Jvvgq4




//categories
###
GET http://localhost:8000/api/categories
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aWN0b3IiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgxOTY1OTR9.jJ_hArU1Sl_KSna9GVVtcwscUgigPaAUOFJtEPNt3Dw


###
GET  http://localhost:8000/api/categories/2

###
//create category

POST http://localhost:8000/api/categories
Content-Type: application/json

{
    "name": "snaks",
    "description": "buns" 
 }

###

PUT http://localhost:8000/api/categories/2
Content-Type: application/json

{
    "name": "food",
    "description": "food items"
}

###
DELETE  http://localhost:8000/api/categories/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aWN0b3IiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgxODM1OTR9.gFFYD_XJ_H8lybnNpI9xTXZp29li7N3XP8pB-Jvvgq4

//address
###
GET http://localhost:8000/api/addresses
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aWN0b3IiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgxOTExMjh9.pbdiJkgEf8yLdRC32iCmIV2hA8w9Nnm0Sl_SD6XNQHw

###
GET  http://localhost:8000/api/addresses/3

###
//create address

POST http://localhost:8000/api/addresses
Content-Type: application/json

{
    "street_address1": "kagio Avenue",
    "street_address2": "Kenyatta Avenue",
    "zip_code": "00100",
    "city_id": 5,
    "delivery_instructions": "Deliver to the receptionist"
  }

###

PUT http://localhost:8000/api/addresses/10
Content-Type: application/json

{
  "id": 10,
  "street_address1": "mwea Avenue",
  "street_address2": "Kenyatta Avenue",
  "zip_code": "00100",
  "city_id": 5,
  "delivery_instructions": "Deliver to the receptionist"
}

###
# Delete an address
DELETE http://localhost:8000/api/addresses/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aWN0b3IiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgxOTExMjh9.pbdiJkgEf8yLdRC32iCmIV2hA8w9Nnm0Sl_SD6XNQHw


//menuitem
###
GET http://localhost:8000/api/menuitems
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aWN0b3IiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgxOTY1OTR9.jJ_hArU1Sl_KSna9GVVtcwscUgigPaAUOFJtEPNt3Dw

###
GET  http://localhost:8000/api/menuitems/22

###
//create menuitem

POST http://localhost:8000/api/menuitems
Content-Type: application/json
    
      {
      
     "name": "Chicken Burger",
     "price": "500",
     "restaurant_id": 4,
     "Category_id": 3,
     "Description": "Chicken Burger",
     "ingredients": "Chicken",
     "active": "Yes"
      }



//driver
###
GET http://localhost:8000/api/drivers
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aWN0b3IiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgxOTExMjh9.pbdiJkgEf8yLdRC32iCmIV2hA8w9Nnm0Sl_SD6XNQHw

###
GET  http://localhost:8000/api/drivers/2

###
//create driver

POST http://localhost:8000/api/drivers
Content-Type: application/json

{
    "id": "29",
    "car_model": "benz",
    "car_make": "GLE",
    "car_year": "2010",
    "name": "lester otieno",
    "phone": "255",
    "email": "lester@gmail.com",
    "car_make": "toyota",
    "user_id": 9
}

###

PUT http://localhost:8000/api/drivers/2
Content-Type: application/json

{
    "name": "john otieno",
    "phone": "255",
    "email": "otieno@gmail.com"
}

###
DELETE  http://localhost:8000/api/drivers/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aWN0b3IiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgxOTExMjh9.pbdiJkgEf8yLdRC32iCmIV2hA8w9Nnm0Sl_SD6XNQHw
//order
###
GET http://localhost:8000/api/orders
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aWN0b3IiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgxOTExMjh9.pbdiJkgEf8yLdRC32iCmIV2hA8w9Nnm0Sl_SD6XNQHw

###
GET  http://localhost:8000/api/orders/2

###
//create order

POST http://localhost:8000/api/orders
Content-Type: application/json

{
    "id": "57",
    "order_date": "2021-09-09",
    "order_status": "Delivered",
    "order_total": "2000",
    "driver": "vinii ",
    "customer": " abdi",
    "menuitem": "food",
    "address": "nairobi",
    "restaurant_id": 4,
    "delivery_address_id": 3,
    "user_id": 8,
    "driver_id": 2,
    "price": 2000,
    "Discount":200,
    "final_price": 1800,
    "Comment": "nice"
}

###

PUT http://localhost:8000/api/orders/1
Content-Type: application/json

{
    "order_date": "2021-09-09",
    "order_status": "pending",
    "order_total": "2000",
    "driver": "lester otieno",
    "customer": "lester otieno",
    "menuitem": "food",
    "address": "nairobi",
}

###
DELETE  http://localhost:8000/api/orders/1

//restaurant
###
GET http://localhost:8000/api/restaurants
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aWN0b3IiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgxOTExMjh9.pbdiJkgEf8yLdRC32iCmIV2hA8w9Nnm0Sl_SD6XNQHw


###
GET http://localhost:8000/api/restaurants/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aWN0b3IiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgxOTExMjh9.pbdiJkgEf8yLdRC32iCmIV2hA8w9Nnm0Sl_SD6XNQHw

###
//create restaurant

POST http://localhost:8000/api/restaurants
Content-Type: application/json

  {
 
   
    "name": "mara",
    "street_address": "Kimathi Street",
    "zip_code": "00100",
    "city_id": 6
    

  }

###

PUT http://localhost:8000/api/restaurants/9

 {

   "name": "tea House",
    "street_address": "Kimathi Street",
    "zip_code": "00100",
    "city_id": 5
  }

###
DELETE  http://localhost:8000/api/restaurants/15
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aWN0b3IiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgxOTExMjh9.pbdiJkgEf8yLdRC32iCmIV2hA8w9Nnm0Sl_SD6XNQHw

//restaurant owner
###
GET http://localhost:8000/api/restaurantsowners
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aWN0b3IiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgxOTExMjh9.pbdiJkgEf8yLdRC32iCmIV2hA8w9Nnm0Sl_SD6XNQHw

###
GET  http://localhost:8000/api/restaurantsowners/2

###
//create restaurant owner

POST http://localhost:8000/api/restaurantsowners
Content-Type: application/json

{
    "id": "2",
    "name": "fundi otieno",
    "phone": "255",
    "email": "fotieno@gmail.com"
}
// oredrmaenu item
###
GET http://localhost:8000/api/menuitems
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aWN0b3IiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgxODM1OTR9.gFFYD_XJ_H8lybnNpI9xTXZp29li7N3XP8pB-Jvvgq4

###
GET  http://localhost:8000/api/menuitems/4

###
//create ordermenuitem

POST http://localhost:8000/api/menuitems
Content-Type: application/json

{
    "id": "4",
    "name": "drinks",
   "Category_id": 2,
   "Description": "hard drinks",
   "active": "false",
   "ingredients": "barley",
    "restaurant_id": 4,
    "order": "mark njoroge",
    "menuitem": "food",
    "quantity": "2",
    "price": "2000"
}

###

PUT http://localhost:8000/api/menuitems/1
Content-Type: application/json

{
    "order": "lester otieno",
    "menuitem": "food",
    "quantity": "2",
    "price": "2000"
}

###
DELETE  http://localhost:8000/api/menuitems/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aWN0b3IiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgxODM1OTR9.gFFYD_XJ_H8lybnNpI9xTXZp29li7N3XP8pB-Jvvgq4
status
//payment


//orderstatus
###
GET http://localhost:8000/api/orders-status
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aWN0b3IiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgxODM1OTR9.gFFYD_XJ_H8lybnNpI9xTXZp29li7N3XP8pB-Jvvgq4

###
GET  http://localhost:8000/api/orders-/3

###
//create orderstatus

POST http://localhost:8000/api/orders-status
Content-Type: application/json

{
    "id": "6",
    "order_id": "5",
    "stats_catalogue_id": "2",
    "name": "active",
    "description": "order is on the way"
}

###

PUT http://localhost:8000/api/orders-status/1
Content-Type: application/json

{
    "name": "pending",
    "description": "order is pending"

}

###
DELETE  http://localhost:8000/api/orders-status/1

//status catalogue

###
GET http://localhost:8000/api/status_catalogs
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aWN0b3IiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgxOTExMjh9.pbdiJkgEf8yLdRC32iCmIV2hA8w9Nnm0Sl_SD6XNQHw


###
GET  http://localhost:8000/api/status_catalogs/2

###
//create statuscatalogue

POST http://localhost:8000/api/status_catalogs
Content-Type: application/json

{
    "id": "3",
    "name": "pending",
    "description": "order is pending"
}

###

PUT http://localhost:8000/api/status_catalogs/1
Content-Type: application/json

{
   "id": "2",
    "name": "pending",
    "description": "order is pending"
}

###
DELETE  http://localhost:8000/api/status_catalogs/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aWN0b3IiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgxOTExMjh9.pbdiJkgEf8yLdRC32iCmIV2hA8w9Nnm0Sl_SD6XNQHw
//comments
###



GET http://localhost:8000/api/comments
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aWN0b3IiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgxODM1OTR9.gFFYD_XJ_H8lybnNpI9xTXZp29li7N3XP8pB-Jvvgq4

###
GET  http://localhost:8000/api/comments/2

###
//create comment

POST http://localhost:8000/api/comments
Content-Type: application/json

{
    "order_id": 1,
    "user_id": 1,
    "comment_text": "nice",
    "is_complaint": "false",
    "is_praise": "true",
    "createdAt": "2021-09-09",
    "updatedAt": "2021-09-09"
}


###

PUT http://localhost:8000/api/comments/1
Content-Type: application/json

{
    "comment": "nice",
    "comment_date": "2021-09-09",
    "menuitem": "food",
    "customer": "lester otieno",
}

###
DELETE  http://localhost:8000/api/comments/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aWN0b3IiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgxODM1OTR9.gFFYD_XJ_H8lybnNpI9xTXZp29li7N3XP8pB-Jvvgq4